# Generated by Django 6.0.6 on 2026-07-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_model', models.CharField(max_length=20)),
                ('machine_no', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token_id', models.CharField(max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=100)),
                ('reading1', models.FloatField(blank=True, null=True)),
                ('reading2', models.FloatField(blank=True, null=True)),
                ('reading3', models.FloatField(blank=True, null=True)),
                ('reading4', models.FloatField(blank=True, null=True)),
                ('reading5', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('allowance', models.FloatField()),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.operator')),
            ],
        ),
    ]
