# Generated by Django 5.2.10 on 2026-07-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_no',
        ),
    ]
