# Generated by Django 5.2.10 on 2026-07-09 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_machine_machine_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestudy',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
